<?php
/**
 * @file
 * Contains hook implementations for the FRP Funding Filter module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function frp_funding_filter_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.frp_funding_filter') {
    return '<p>' . t('Provides dynamic filtering of funding opportunities by region and category.') . '</p>';
  }
}